import { Provider } from '@angular/core';
import {
  provideLucideIcons,
  LucideActivity,
  LucideArrowRight,
  LucideBanknote,
  LucideBell,
  LucideBellOff,
  LucideBriefcase,
  LucideCamera,
  LucideCircleHelp,
  LucideIdCard,
  LucideLightbulb,
  LucidePencil,
  LucideTriangleAlert,
  LucideCalendarCheck,
  LucideCalendarClock,
  LucideCalendarDays,
  LucideCalendarOff,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleCheck,
  LucideCirclePlay,
  LucideClipboardList,
  LucideClock,
  LucideCreditCard,
  LucideDownload,
  LucideEye,
  LucideEyeOff,
  LucideFileText,
  LucideFilter,
  LucideHeadphones,
  LucideHeartPulse,
  LucideHistory,
  LucideHouse,
  LucideInfo,
  LucideLanguages,
  LucideLayoutDashboard,
  LucideLock,
  LucideLogOut,
  LucideMail,
  LucideMapPin,
  LucideMenu,
  LucideMessageSquare,
  LucidePhone,
  LucidePill,
  LucidePlus,
  LucideRefreshCw,
  LucideSearch,
  LucideSettings,
  LucideShield,
  LucideShieldCheck,
  LucideStar,
  LucideStethoscope,
  LucideTrash2,
  LucideUser,
  LucideUserRound,
  LucideUsers,
  LucideUserX,
  LucideVideo,
  LucideWallet,
  LucideWifiOff,
  LucideX,
  LucideZap,
} from '@lucide/angular';

/**
 * The Lucide icons registered app-wide and usable as `<sd-icon name="...">`.
 * Names are the kebab-case Lucide names, e.g. `LucideCalendarDays` => "calendar-days".
 *
 * Add the icons your features need here — keeping the set curated keeps bundles
 * small. Browse the full set at https://lucide.dev/icons.
 */
export const SUPADOC_ICONS = [
  LucideActivity,
  LucideHouse,
  LucideLayoutDashboard,
  LucideUser,
  LucideUserRound,
  LucideUserX,
  LucideUsers,
  LucideStethoscope,
  LucideHeartPulse,
  LucidePill,
  LucideBellOff,
  LucideCamera,
  LucideCircleHelp,
  LucideIdCard,
  LucideLightbulb,
  LucidePencil,
  LucideTriangleAlert,
  LucideBriefcase,
  LucideCalendarDays,
  LucideCalendarCheck,
  LucideCalendarClock,
  LucideCalendarOff,
  LucideChevronDown,
  LucideChevronRight,
  LucideCirclePlay,
  LucideCircleCheck,
  LucideClipboardList,
  LucideClock,
  LucideCreditCard,
  LucideDownload,
  LucideFileText,
  LucideFilter,
  LucideHeadphones,
  LucideHistory,
  LucideInfo,
  LucideLanguages,
  LucideMapPin,
  LucideMessageSquare,
  LucideRefreshCw,
  LucideStar,
  LucideTrash2,
  LucideVideo,
  LucideWifiOff,
  LucideZap,
  LucideBell,
  LucideBanknote,
  LucideWallet,
  LucideSearch,
  LucideSettings,
  LucideMenu,
  LucidePlus,
  LucideArrowRight,
  LucideCheck,
  LucideX,
  LucideLogOut,
  LucideMail,
  LucideLock,
  LucidePhone,
  LucideEye,
  LucideEyeOff,
  LucideShield,
  LucideShieldCheck,
];

/**
 * Registers the Supadoc Lucide icon set. Add to an app's `app.config.ts`
 * providers so `<sd-icon name="...">` can resolve icons by name.
 */
export function provideSupadocIcons(): Provider {
  return provideLucideIcons(...SUPADOC_ICONS);
}
